---

- name: Remove podman, buildah
  yum:
    name: 
      - podman
      - buildah
    state: absent
  when: ansible_distribution_major_version == "8"

- name: Add docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install docker engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: latest
  
  
