---
name: CI
on: [push]

jobs:
  molecule-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu:20.04
          - centos:8
        role:
          - packages/docker
    
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker
      
      - name: Test with molecule
        run: molecule test
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: ./roles/${{ matrix.role }}
